### PR TITLE
feat: add tab component

### PR DESCRIPTION
**Pull request by kurokn**

### CODE REVIEW

**Review by junminahn — COMMENTED** [review]
any reason you want to call it `Tab` instead of `Tabs`?

**Comment by kurokn** [comment]
because the `Tabs` is a import name by `rc-tabs` library, seems it report error on declaration

**Comment by kurokn** [comment]
> any reason you want to call it `Tab` instead of `Tabs`? and without the `!important;` rule, the styles are not applied properly?

because the Tabs is a import name by rc-tabs library, seems it report error on declaration;
i just directly copied the styles from sso-request, yeah you're right, i can update;

**Comment by kurokn** [comment]
> any reason you want to call it `Tab` instead of `Tabs`? and without the `!important;` rule, the styles are not applied properly?

because the Tabs is a import name by rc-tabs library, seems it report error on declaration;
i just directly copied the styles from sso-request, yeah you're right, i can update;

**Review by junminahn — APPROVED** [review]

**Pull request merged**
